version: '3'

services:
    nginx:
        image: nginx:1.14
        ports:
            - "${NGINX_HOST}:${NGINX_PORT}:80"
        volumes:
            - ./:/app:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

    php:
        build:
            context: docker/php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./:/app:cached
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
            - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:cached
        user: ${DOCKER_UID}
        env_file: .env
        extra_hosts:
            - "host:${DOCKER_ADDRESS}"
        cap_add:
            - SYS_PTRACE

    markup:
        build: docker/markup
        user: ${DOCKER_UID}
        volumes:
            - ./:/app:cached
        command: bash -c "npm install; bower install; gulp external"
        environment:
            NODE_ENV: ${MARKUP_ENV}
