swagger: '2.0'
info:
  description: API для работы сайта Cinema5
  version: 1.0.0
  title: Cinema5 API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: cinema5.swagger.io
tags:
  - name: cities
    description: Everything about city
  - name: discounts
    description: Everything about discounts
schemes:
  - http
paths:
  /promo/:
    get:
      summary: Вывод блока промо на главной
      operationId: getPromo
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Promo'
  /cities/:
    get:
      tags:
        - cities
      summary: Список городов
      operationId: getCities
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Cities'
  /format/:
    get:
      summary: Вывод списка форматов для блока фильтрации
      operationId: getFormat
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Formats'
  /time/:
    get:
      summary: Вывод времени для блока фильтрации на странице рассписание
      operationId: getTime
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Time'
  /hall_type/:
    get:
      summary: Вывод типов зала для блока фильтрации
      operationId: getHallType
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Hall'
  '/vacancy/{vacancyId}/':
    get:
      summary: Вывод инофрмации о конкретной вакансии по id
      operationId: getVacancy
      produces:
        - application/json
      parameters:
        - name: vacancyId
          in: path
          description: ID of vacancy
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/CinemaVacancies'
  /films/paginate/:
    get:
      summary: Вывод отфильрованного списка фильмов с пагинацией
      operationId: getFilmsPaginate
      produces:
        - application/json
      parameters:
        - name: page
          in: query
          type: integer
          format: int64
        - name: maxPerPage
          in: query
          type: integer
          format: int64
        - name: sortType
          in: query
          type: integer
          format: int64
        - name: cityId
          in: query
          type: integer
          format: int64
        - name: cinemaId
          in: query
          type: integer
          format: int64
        - name: format
          in: query
          type: integer
          format: int64
        - name: time
          in: query
          type: integer
          format: int64
        - name: hall_type
          in: query
          type: integer
          format: int64
        - name: labels
          in: query
          type: array
          items:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/FilmsList'
        '400':
          description: Invalid parameters
        '404':
          description: Films not found
  /films/open_sale/:
    get:
      summary: 'Список фильмов и мероприятий для блока ''Открыта продажа'' '
      operationId: getFilmsOpenSale
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/FilmsOpenSaleList'
  '/cinemas/{cityId}/':
    get:
      tags:
        - cinemas
      summary: Список кинотеатров по id города
      operationId: getCinemas
      produces:
        - application/json
      parameters:
        - name: cityId
          in: path
          description: ID of city
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Cinemas'
        '400':
          description: Invalid ID supplied
        '404':
          description: Cinemas not found
  '/cinema/{cinemaId}/':
    get:
      tags:
        - cinemas
      summary: Вывод информации о конткретном кинотетре по id
      operationId: getCinema
      produces:
        - application/json
      parameters:
        - name: cinemaId
          in: path
          description: ID of cinema
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Cinema'
        '400':
          description: Invalid ID supplied
        '404':
          description: Cinemas not found
  /discounts/paginate/:
    get:
      tags:
        - discounts
      summary: Список акций и скидок с пагинацией
      operationId: getDiscounts
      produces:
        - application/json
      parameters:
        - name: page
          in: query
          type: integer
          format: int64
        - name: maxPerPage
          in: query
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/DiscountsPaginate'
        '404':
          description: discounts not found
  '/discount/{discountId}/':
    get:
      tags:
        - discounts
      summary: Выввод информации об акции или скидки по её id
      operationId: getDiscount
      produces:
        - application/json
      parameters:
        - name: discountId
          in: path
          description: ID of discount
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Discount'
        '404':
          description: discount not found
  /lables/:
    get:
      summary: Вывод списка меток
      operationId: getLables
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/FilmLables'
        '404':
          description: discount not found
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Cities:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
  Formats:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
  Time:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
  Hall:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
  Cinemas:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      phone:
        type: integer
        format: int64
        example: '89631234567'
      email:
        type: string
        example: qwerty@mail.ru
      address:
        type: string
        example: >-
          г. Санкт-Петербург, Малый проспект В.О., д.88, ТРК «Шкиперский Молл»,
          3​-й​ этаж.
      work_time:
        type: string
        example: 'Пн-Пт 10:00 - 21:00 Сб-Вс 9:00 - 19:00'
      image_id:
        type: integer
        format: int64
      panorama:
        type: integer
        format: int64
  Cinema:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      phone:
        type: integer
        format: int64
        example: '89631234567'
      email:
        type: string
        example: qwerty@mail.ru
      address:
        type: string
        example: >-
          г. Санкт-Петербург, Малый проспект В.О., д.88, ТРК «Шкиперский Молл»,
          3​-й​ этаж.
      work_time:
        type: string
        example: 'Пн-Пт 10:00 - 21:00 Сб-Вс 9:00 - 19:00'
      image_id:
        type: integer
        format: int64
      panorama:
        type: integer
        format: int64
      content_id:
        type: integer
        format: int64
      cinema_rooms:
        type: array
        xml:
          name: cinema_rooms
          wrapped: true
        items:
          $ref: '#/definitions'
      vacancies:
        type: array
        xml:
          name: vacancies
          wrapped: true
        items:
          $ref: '#/definitions/CinemaVacancies'
      gallery_id:
        type: integer
        format: int64
  CinemaVacancies:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
        example: Бармен
      salary:
        type: string
        example: от 20 000 до 35 000 ₽
      content_id:
        type: integer
        format: int64
  FilmsList:
    type: object
    properties:
      paginate:
        type: object
        properties:
          current:
            type: integer
            format: int64
          next:
            type: integer
            format: int64
          pages:
            type: integer
            format: int64
      films:
        type: array
        xml:
          name: films
          wrapped: true
        items:
          $ref: '#/definitions/ListOfFilms'
  FilmLables:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
  FilmSessions:
    type: object
    properties:
      id:
        type: integer
        format: int64
      format:
        type: string
      start_time:
        type: string
      cost:
        type: integer
        format: int64
      is_vip:
        type: boolean
  ListOfFilms:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      poster_id:
        type: integer
        format: int64
      age_limit:
        type: integer
        format: int64
      genre:
        type: string
        example: 'Драма, военный, исторический'
      labels:
        type: array
        xml:
          name: labels
          wrapped: true
        items:
          $ref: '#/definitions/FilmLables'
      duration:
        type: string
        example: 1 час 35 мин.
      sessions:
        type: array
        xml:
          name: sessions
          wrapped: true
        items:
          $ref: '#/definitions/FilmSessions'
  FilmsOpenSaleList:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      caption:
        type: string
      poster_id:
        type: integer
        format: int64
      age_limit:
        type: integer
        format: int64
      genre:
        type: string
        example: 'Драма, военный, исторический'
      duration:
        type: string
        example: 1 час 35 мин.
      description:
        type: integer
        format: int64
      sessions:
        type: array
        xml:
          name: sessions
          wrapped: true
        items:
          $ref: '#/definitions/FilmSessions'
  DiscountsPaginate:
    type: object
    properties:
      paginate:
        type: object
        properties:
          current:
            type: integer
            format: int64
          next:
            type: integer
            format: int64
          pages:
            type: integer
            format: int64
      discounts:
        type: array
        xml:
          name: discounts
          wrapped: true
        items:
          $ref: '#/definitions/ListOfDiscounts'
  ListOfDiscounts:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      image_id:
        type: integer
        format: int64
      text_short:
        type: integer
        format: int64
  Discount:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      image_id:
        type: integer
        format: int64
      text_short:
        type: integer
        format: int64
      text:
        type: integer
        format: int64
  Promo:
    type: object
    properties:
      id:
        type: integer
        format: int64
      is_event:
        type: boolean
      title:
        type: string
      image_id:
        type: integer
        format: int64
      text_short:
        type: integer
        format: int64
      video:
        type: string
      sessions:
        type: array
        xml:
          name: sessions
          wrapped: true
        items:
          $ref: '#/definitions/FilmSessions'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
