services:
    Creonit\RestBundle\EventListener\RestListener:
        arguments: ['@service_container']
        tags:
            - {name: kernel.event_listener, event: kernel.response}
            - {name: kernel.event_listener, event: kernel.request}
            - {name: kernel.event_listener, event: kernel.exception}

    Creonit\RestBundle\Handler\RestHandler:
        arguments: ['@service_container']
        shared: false

    Creonit\RestBundle\Serializer\XmlEncoder:
        tags:
            - {name: serializer.encoder, priority: 10}

    rest.handler:
        alias: Creonit\RestBundle\Handler\RestHandler