admin:
    resource: "@CreonitAdminBundle/Controller/"
    type:     annotation
    prefix: /admin

api:
    resource: "@AppBundle/Controller/Api/"
    type:     annotation
    prefix: /api

#creonit_markup:
#    resource: .
#    type: markup

creonit_page:
    resource: .
    type: extra