config:
    required: true

database:
    +:
        name: default
        namespace: AppBundle\Model
        defaultIdMethod: native
        identifierQuoting: true

    +vendor:
        type: mysql
        parameters:
            Engine: InnoDB
            Charset: utf8

    +behavior:
        - auto_add_pk
        - cache

    user:
        email: text
        name: text
        +behavior:
            - timestampable

    user_restore_token:
        user_id: int > user.id
        code: varchar(64) key
        expired_at: datetime
        used: bool = 0
        +behavior:
            - timestampable

    # storage
    storage_section:
        section_id: - int > storage_section.id
        title: text
        +behavior:
            - sortable

    storage:
        section_id: int > storage_section.id
        title: text
        code: varchar(32) key(6)
        multiresult: bool
        visible: bool = 1
        +behavior:
            - sortable

    storage_field:
        storage_id: int > storage.id
        type: tinyint(3)
        title: text
        code: varchar(32) key(6)
        visible: bool = 1
        +behavior:
            - sortable

    storage_option:
        field_id: int > storage_field.id
        title: text
        +behavior:
            - sortable

    storage_result:
        storage_id: int > storage.id
        visible: bool = 1
        +behavior:
            - sortable: storage_id

    storage_value:
        result_id: int > storage_result.id
        field_id: int > storage_field.id
        option_id: - int > storage_option.id
        text: text
        bool: bool
        +behavior:
            - image
            - gallery
            - file
            - video

    # form
    form:
        mailing_template_id: - int > mailing_template.id(setnull)
        title: text
        code: varchar(32)
        notification_email: text
        success_text: text
        visible: bool = 1
        +behavior:
            - sortable

    form_field:
        form_id: int > form.id
        title: text
        code: text
        type: tinyint
        required: bool
        validation_type: tinyint
        file_extensions: text
        max_file_size: int
        regexp: text
        required_error: text
        invalid_error: text
        visible: bool = 1
        +behavior:
            - sortable: form_id

    form_field_option:
        title: text
        field_id: int > form_field.id
        visible: bool = 1
        +behavior:
            - sortable: field_id

    form_result:
        form_title: text
        # target_id: - int > holder.id(setnull)
        form_id: int > form.id
        user_id: - int > user.id
        file_id: - int > file.id
        status: tinyint
        url_from: text
        answer: text
        notice: text
        published: bool
        ip_address: text
        read: bool
        answered_at: datetime
        +behavior:
            - timestampable

    form_result_field:
        result_id: int > form_result.id
        form_id: int > form.id
        field_id: int > form_field.id
        value: text
        file_path: text
        file_id: - int > file.id
        +behavior:
            - sortable