# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        creonit_user:
            id: creonit.security.user_provider

    encoders:
        AppBundle\Model\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # admin:
        #     pattern:    ^/admin
        #     http_basic: ~
        #     provider:   creonit_user

        main:
            anonymous: ~

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }