services:
    AppBundle\Admin\AdminPlugin:
        arguments: ["@service_container"]
        tags: [{name: 'creonit_admin.plugin', priority: -10}]
        public: false

    AppBundle\Admin\:
        resource: '../../src/AppBundle/Admin/*/*Module.php'
        public: false
        tags: ['creonit_admin.module']

    AppBundle\Normalizer\:
        resource: '../../src/AppBundle/Normalizer/*Normalizer.php'
        public: false
        arguments: ['@service_container']
        calls:
            - [setSerializer, ['@serializer']]
        tags: ['serializer.normalizer']

    AppBundle\Event\EventSubscriber:
        arguments: ['@service_container', '@router']
        public: false
        tags: [ {name: kernel.event_subscriber} ]

    app.asset.gulp_buster_version_strategy:
        class: AppBundle\Asset\GulpBusterVersionStrategy
        arguments:
            - "%kernel.project_dir%/var/busters.json"
            - "%%s?%%s"
            - "%asset_version%"
        public: false

    app.authorization:
        class: AppBundle\Service\AuthorizationService
        arguments: ["@service_container"]

    app.storage:
        class: AppBundle\Service\StorageService
        arguments: ['@service_container']

    app.user:
        class: AppBundle\Service\UserService
        arguments: ['@service_container']

    app.user_restore:
        class: AppBundle\Service\UserRestoreService
        arguments: ['@service_container']

    app.form_service:
        class: AppBundle\Service\FormService
        arguments: ['@service_container', '@request_stack']

    app.page:
        class: AppBundle\Service\PageService
        arguments: ['@service_container']