services:
    app.authorization:
        class: AppBundle\Service\Authorization
        arguments: ["@service_container"]


#    app.request_listener:
#        class: AppBundle\EventListener\RequestListener
#        arguments: ['@service_container']
#        tags: [ {name: kernel.event_listener, event: kernel.request} ]

    app.response_listener:
        class: AppBundle\EventListener\RestListener
        arguments: ['@service_container']
        tags:
            - {name: kernel.event_listener, event: kernel.response}
            - {name: kernel.event_listener, event: kernel.request}
            - {name: kernel.event_listener, event: kernel.exception}